version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d  # Mount init script
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: taskdb
      DB_USER: admin
      DB_PASS: admin
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
