version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
